apiVersion: v1
kind: ReplicationController
metadata:
  namespace: radio
  name: icecast-srv
  labels:
    app: icecast-srv
spec:
  replicas: 1
  selector:
    app: icecast-srv
  template:
    metadata:
      labels:
        app: icecast-srv
    spec:
      containers:
      - name: icecast-srv
        image: localhost:5000/icecast:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: radio
  name: icecast-srv
spec:
  type: LoadBalancer
  clusterIP: 10.105.178.10
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
  selector:
    app: icecast-srv
---
