apiVersion: v1
kind: ReplicationController
metadata:
  namespace: radio
  name: ices-station
  labels:
    app: ices-station
spec:
  replicas: 1
  selector:
    app: ices-station
  template:
    metadata:
      labels:
        app: ices-station
    spec:
      containers:
      - name: ices-station
        image: localhost:5000/ices:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  namespace: radio
  name: ices-station
spec:
  type: LoadBalancer
  clusterIP: 10.105.178.11
  ports:
    - protocol: TCP
      name: http
      port: 8001
      targetPort: 8001
  selector:
    app: ices-station
---
